version: 2
updates:
- package-ecosystem: bundler
  target-branch: "main"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  labels:
  - "Type: Chore"