Style/AccessModifierIndentation:
  Enabled: true
Style/AccessorMethodName:
  Enabled: true
Style/Alias:
  Enabled: true
Style/AlignArray:
  Enabled: true
Style/AlignHash:
  Enabled: true
Style/AlignParameters:
  Enabled: true
Style/AndOr:
  Enabled: true
Style/ArrayJoin:
  Enabled: true
Style/AsciiComments:
  Enabled: true
Style/AsciiIdentifiers:
  Enabled: true
Style/Attr:
  Enabled: true
Style/BeginBlock:
  Enabled: true
Style/BarePercentLiterals:
  Enabled: true
Style/BlockComments:
  Enabled: true
Style/BlockEndNewline:
  Enabled: true
Style/BlockDelimiters:
  Enabled: true
Style/BracesAroundHashParameters:
  Enabled: true
Style/CaseEquality:
  Enabled: true
Style/CaseIndentation:
  Enabled: true
Style/CharacterLiteral:
  Enabled: true
Style/ClassAndModuleCamelCase:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
Style/ClassCheck:
  Enabled: true
Style/ClassMethods:
  Enabled: true
Style/ClassVars:
  Enabled: true
Style/ClosingParenthesisIndentation:
  Enabled: true
Style/ColonMethodCall:
  Enabled: true
Style/CommandLiteral:
  Enabled: true
Style/CommentAnnotation:
  Enabled: true
Style/CommentIndentation:
  Enabled: true
Style/ConditionalAssignment:
  Enabled: true
Style/ConstantName:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/DeprecatedHashMethods:
  Enabled: true
Style/Documentation:
  Enabled: true
Style/DotPosition:
  Enabled: true
Style/DoubleNegation:
  Enabled: true
Style/EachWithObject:
  Enabled: true
Style/ElseAlignment:
  Enabled: true
Style/EmptyElse:
  Enabled: true
Style/EmptyLineBetweenDefs:
  Enabled: true
Style/EmptyLines:
  Enabled: true
Style/EmptyLinesAroundAccessModifier:
  Enabled: true
Style/EmptyLinesAroundBlockBody:
  Enabled: true
Style/EmptyLinesAroundClassBody:
  Enabled: true
Style/EmptyLinesAroundModuleBody:
  Enabled: true
Style/EmptyLinesAroundMethodBody:
  Enabled: true
Style/EmptyLiteral:
  Enabled: true
Style/EndBlock:
  Enabled: true
Style/EndOfLine:
  Enabled: true
Style/EvenOdd:
  Enabled: true
Style/ExtraSpacing:
  Enabled: true
Style/FileName:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Style/InitialIndentation:
  Enabled: true
Style/FirstParameterIndentation:
  Enabled: true
Style/FlipFlop:
  Enabled: true
Style/For:
  Enabled: true
Style/FormatString:
  Enabled: true
Style/GlobalVars:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/IfInsideElse:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: true
Style/IfWithSemicolon:
  Enabled: true
Style/IndentationConsistency:
  Enabled: true
Style/IndentationWidth:
  Enabled: true
Style/IdenticalConditionalBranches:
  Enabled: true
Style/IndentArray:
  Enabled: true
Style/IndentAssignment:
  Enabled: true
Style/IndentHash:
  Enabled: true
Style/InfiniteLoop:
  Enabled: true
Style/Lambda:
  Enabled: true
Style/LambdaCall:
  Enabled: true
Style/LeadingCommentSpace:
  Enabled: true
Style/LineEndConcatenation:
  Enabled: true
Style/MethodCallParentheses:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: true
Style/MethodName:
  Enabled: true
Style/ModuleFunction:
  Enabled: true
Style/MultilineBlockChain:
  Enabled: true
Style/MultilineBlockLayout:
  Enabled: true
Style/MultilineIfThen:
  Enabled: true
Style/MultilineMethodCallIndentation:
  Enabled: true
Style/MultilineOperationIndentation:
  Enabled: true
Style/MultilineTernaryOperator:
  Enabled: true
Style/MutableConstant:
  Enabled: true
Style/NegatedIf:
  Enabled: true
Style/NegatedWhile:
  Enabled: true
Style/NestedModifier:
  Enabled: true
Style/NestedParenthesizedCalls:
  Enabled: true
Style/NestedTernaryOperator:
  Enabled: true
Style/Next:
  Enabled: true
Style/NilComparison:
  Enabled: true
Style/NonNilCheck:
  Enabled: true
Style/Not:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/OneLineConditional:
  Enabled: true
Style/OpMethod:
  Enabled: true
Style/OptionalArguments:
  Enabled: true
Style/ParallelAssignment:
  Enabled: true
Style/ParenthesesAroundCondition:
  Enabled: true
Style/PercentLiteralDelimiters:
  Enabled: true
Style/PercentQLiterals:
  Enabled: true
Style/PerlBackrefs:
  Enabled: true
Style/PredicateName:
  Enabled: true
Style/Proc:
  Enabled: true
Style/RaiseArgs:
  Enabled: true
Style/RedundantBegin:
  Enabled: true
Style/RedundantException:
  Enabled: true
Style/RedundantFreeze:
  Enabled: true
Style/RedundantParentheses:
  Enabled: true
Style/RedundantReturn:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/RegexpLiteral:
  Enabled: true
Style/RescueEnsureAlignment:
  Enabled: true
Style/RescueModifier:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/Semicolon:
  Enabled: true
Style/SignalException:
  Enabled: true
Style/SingleLineBlockParams:
  Enabled: true
Style/SingleLineMethods:
  Enabled: true
Style/SpaceBeforeFirstArg:
  Enabled: true
Style/SpaceAfterColon:
  Enabled: true
Style/SpaceAfterComma:
  Enabled: true
Style/SpaceAfterMethodName:
  Enabled: true
Style/SpaceAfterNot:
  Enabled: true
Style/SpaceAfterSemicolon:
  Enabled: true
Style/SpaceBeforeBlockBraces:
  Enabled: true
Style/SpaceBeforeComma:
  Enabled: true
Style/SpaceBeforeComment:
  Enabled: true
Style/SpaceBeforeSemicolon:
  Enabled: true
Style/SpaceInsideBlockBraces:
  Enabled: true
Style/SpaceAroundBlockParameters:
  Enabled: true
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true
Style/SpaceAroundKeyword:
  Enabled: true
Style/SpaceAroundOperators:
  Enabled: true
Style/SpaceInsideBrackets:
  Enabled: true
Style/SpaceInsideHashLiteralBraces:
  Enabled: true
Style/SpaceInsideParens:
  Enabled: true
Style/SpaceInsideRangeLiteral:
  Enabled: true
Style/SpaceInsideStringInterpolation:
  Enabled: true
Style/SpecialGlobalVars:
  Enabled: true
Style/StabbyLambdaParentheses:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true
Style/StructInheritance:
  Enabled: true
Style/SymbolLiteral:
  Enabled: true
Style/SymbolProc:
  Enabled: true
Style/Tab:
  Enabled: true
Style/TrailingBlankLines:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
Style/TrailingCommaInLiteral:
  Enabled: true
Style/TrailingWhitespace:
  Enabled: true
Style/TrivialAccessors:
  Enabled: true
Style/UnlessElse:
  Enabled: true
Style/UnneededCapitalW:
  Enabled: true
Style/UnneededInterpolation:
  Enabled: true
Style/UnneededPercentQ:
  Enabled: true
Style/TrailingUnderscoreVariable:
  Enabled: true
Style/VariableInterpolation:
  Enabled: true
Style/VariableName:
  Enabled: true
Style/WhenThen:
  Enabled: true
Style/WhileUntilDo:
  Enabled: true
Style/WhileUntilModifier:
  Enabled: true
Style/WordArray:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true
Metrics/AbcSize:
  Enabled: true
Metrics/BlockNesting:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
Metrics/ModuleLength:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/LineLength:
  Enabled: true
Metrics/MethodLength:
  Enabled: true
Metrics/ParameterLists:
  Enabled: true
Metrics/PerceivedComplexity:
  Enabled: true
Lint/AmbiguousOperator:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
Lint/BlockAlignment:
  Enabled: true
Lint/CircularArgumentReference:
  Enabled: true
Lint/ConditionPosition:
  Enabled: true
Lint/Debugger:
  Enabled: true
Lint/DefEndAlignment:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/DuplicatedKey:
  Enabled: true
Lint/EachWithObjectArgument:
  Enabled: true
Lint/ElseLayout:
  Enabled: true
Lint/EmptyEnsure:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/EndAlignment:
  Enabled: true
Lint/EndInMethod:
  Enabled: true
Lint/EnsureReturn:
  Enabled: true
Lint/Eval:
  Enabled: true
Lint/FloatOutOfRange:
  Enabled: true
Lint/FormatParameterMismatch:
  Enabled: true
Lint/HandleExceptions:
  Enabled: true
Lint/ImplicitStringConcatenation:
  Enabled: true
Lint/IneffectiveAccessModifier:
  Enabled: true
Lint/InvalidCharacterLiteral:
  Enabled: true
Lint/LiteralInCondition:
  Enabled: true
Lint/LiteralInInterpolation:
  Enabled: true
Lint/Loop:
  Enabled: true
Lint/NestedMethodDefinition:
  Enabled: true
Lint/NextWithoutAccumulator:
  Enabled: true
Lint/NonLocalExitFromIterator:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Enabled: true
Lint/RandOne:
  Enabled: true
Lint/RequireParentheses:
  Enabled: true
Lint/RescueException:
  Enabled: true
Lint/ShadowingOuterLocalVariable:
  Enabled: true
Lint/StringConversionInInterpolation:
  Enabled: true
Lint/UnderscorePrefixedVariableName:
  Enabled: true
Lint/UnneededDisable:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/UselessComparison:
  Enabled: true
Lint/UselessElseWithoutRescue:
  Enabled: true
Lint/UselessSetterCall:
  Enabled: true
Lint/Void:
  Enabled: true
Performance/Casecmp:
  Enabled: true
Performance/CaseWhenSplat:
  Enabled: true
Performance/Count:
  Enabled: true
Performance/Detect:
  Enabled: true
Performance/DoubleStartEndWith:
  Enabled: true
Performance/EndWith:
  Enabled: true
Performance/FixedSize:
  Enabled: true
Performance/FlatMap:
  Enabled: true
  EnabledForFlattenWithoutParams: false
Performance/HashEachMethods:
  Enabled: true
Performance/LstripRstrip:
  Enabled: true
Performance/RangeInclude:
  Enabled: true
Performance/RedundantBlockCall:
  Enabled: true
Performance/RedundantMatch:
  Enabled: true
Performance/RedundantMerge:
  Enabled: true
Performance/RedundantSortBy:
  Enabled: true
Performance/ReverseEach:
  Enabled: true
Performance/Sample:
  Enabled: true
Performance/Size:
  Enabled: true
Performance/StartWith:
  Enabled: true
Performance/StringReplacement:
  Enabled: true
Performance/TimesMap:
  Enabled: true
Rails/ActionFilter:
  Enabled: true
Rails/Date:
  Enabled: true
Rails/Delegate:
  Enabled: true
Rails/FindBy:
  Enabled: true
Rails/FindEach:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: true
Rails/Output:
  Enabled: true
Rails/PluralizationGrammar:
  Enabled: true
Rails/ReadWriteAttribute:
  Enabled: true
Rails/ScopeArgs:
  Enabled: true
Rails/TimeZone:
  Enabled: true
Rails/Validation:
  Enabled: true
