---
Bundler/DuplicatedGem:
  Enabled: false
Bundler/GemComment:
  Enabled: false
Bundler/InsecureProtocolSource:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Gemspec/DuplicatedAssignment:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/RubyVersionGlobalsUsage:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
Layout/AlignArguments:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/ClassStructure:
  Enabled: false
Layout/ClosingHeredocIndentation:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/ConditionPosition:
  Enabled: false
Layout/DefEndAlignment:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Layout/EmptyLinesAroundBeginBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/FirstArrayElementLineBreak:
  Enabled: false
Layout/FirstHashElementLineBreak:
  Enabled: false
Layout/FirstMethodArgumentLineBreak:
  Enabled: false
Layout/FirstMethodParameterLineBreak:
  Enabled: false
Layout/HeredocArgumentClosingParenthesis:
  Enabled: false
Layout/IndentAssignment:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/IndentFirstArgument:
  Enabled: false
Layout/IndentFirstArrayElement:
  Enabled: false
Layout/IndentFirstHashElement:
  Enabled: false
Layout/IndentFirstParameter:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Layout/InitialIndentation:
  Enabled: false
Layout/LeadingBlankLines:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/MultilineArrayLineBreaks:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Layout/MultilineHashBraceLayout:
  Enabled: false
Layout/MultilineHashKeyLineBreaks:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/SpaceAfterColon:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAfterMethodName:
  Enabled: false
Layout/SpaceAfterNot:
  Enabled: false
Layout/SpaceAfterSemicolon:
  Enabled: false
Layout/SpaceAroundBlockParameters:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/SpaceAroundKeyword:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceBeforeComma:
  Enabled: false
Layout/SpaceBeforeComment:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceBeforeSemicolon:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideRangeLiteral:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  Enabled: false
Layout/Tab:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/BigDecimalNew:
  Enabled: false
Lint/BooleanSymbol:
  Enabled: false
Lint/CircularArgumentReference:
  Enabled: false
Lint/Debugger:
  Enabled: false
Lint/DeprecatedClassMethods:
  Enabled: false
Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false
Lint/DuplicateCaseCondition:
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false
Lint/DuplicatedKey:
  Enabled: false
Lint/EachWithObjectArgument:
  Enabled: false
Lint/ElseLayout:
  Enabled: false
Lint/EmptyEnsure:
  Enabled: false
Lint/EmptyExpression:
  Enabled: false
Lint/EmptyInterpolation:
  Enabled: false
Lint/EmptyWhen:
  Enabled: false
Lint/EndInMethod:
  Enabled: false
Lint/EnsureReturn:
  Enabled: false
Lint/ErbNewArguments:
  Enabled: false
Lint/FlipFlop:
  Enabled: false
Lint/FloatOutOfRange:
  Enabled: false
Lint/FormatParameterMismatch:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/HeredocMethodCallPosition:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Enabled: false
Lint/InheritException:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/InterpolationCheck:
  Enabled: false
Lint/LiteralAsCondition:
  Enabled: false
Lint/LiteralInInterpolation:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
Lint/MultipleCompare:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Lint/NestedPercentLiteral:
  Enabled: false
Lint/NextWithoutAccumulator:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Lint/OrderedMagicComments:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/PercentStringArray:
  Enabled: false
Lint/PercentSymbolArray:
  Enabled: false
Lint/RandOne:
  Enabled: false
Lint/RedundantWithIndex:
  Enabled: false
Lint/RedundantWithObject:
  Enabled: false
Lint/RegexpAsCondition:
  Enabled: false
Lint/RequireParentheses:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/RescueType:
  Enabled: false
Lint/ReturnInVoidContext:
  Enabled: false
Lint/SafeNavigationConsistency:
  Enabled: false
Lint/SafeNavigationChain:
  Enabled: false
Lint/SafeNavigationWithEmpty:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Lint/ShadowedArgument:
  Enabled: false
Lint/ShadowedException:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/StringConversionInInterpolation:
  Enabled: false
Lint/Syntax:
  Enabled: false
Lint/ToJSON:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false
Lint/UnneededCopDisableDirective:
  Enabled: false
Lint/UnneededCopEnableDirective:
  Enabled: false
Lint/UnneededRequireStatement:
  Enabled: false
Lint/UnneededSplatExpansion:
  Enabled: false
Lint/UnreachableCode:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Lint/UriRegexp:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/UselessComparison:
  Enabled: false
Lint/UselessElseWithoutRescue:
  Enabled: false
Lint/UselessSetterCall:
  Enabled: false
Lint/Void:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/AsciiIdentifiers:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
Naming/ConstantName:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterCase:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/UncommunicativeBlockParamName:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/VariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/Alias:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/ArrayJoin:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Attr:
  Enabled: false
Style/AutoResourceCleanup:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BeginBlock:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Style/ClassMethods:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/ColonMethodDefinition:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/ConstantVisibility:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/Dir:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyBlockParameter:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLambdaParameter:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/EndBlock:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FloatDivision:
  Enabled: false
Style/For:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IfUnlessModifierOfIfUnless:
  Enabled: false
Style/IfWithSemicolon:
  Enabled: false
Style/ImplicitRuntimeError:
  Enabled: false
Style/InfiniteLoop:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/IpAddresses:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/MinMax:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineIfThen:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineMethodSignature:
  Enabled: false
Style/MultilineMemoization:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedUnless:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/NestedModifier:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/Next:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/OrAssignment:
  Enabled: false
Style/OptionHash:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RandomWithOffset:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantConditional:
  Enabled: false
Style/RedundantException:
  Enabled: false
Style/RedundantFreeze:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RedundantSortBy:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/ReturnNil:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/Sample:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/Send:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StringMethods:
  Enabled: false
Style/Strip:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TrailingBodyOnClass:
  Enabled: false
Style/TrailingBodyOnMethodDefinition:
  Enabled: false
Style/TrailingBodyOnModule:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingMethodEndStatement:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/UnneededCapitalW:
  Enabled: false
Style/UnneededCondition:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/UnneededSort:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
Style/VariableInterpolation:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Security/Eval:
  Enabled: false
Security/JSONLoad:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
Security/Open:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
